"use client";
import React from "react";
import { Button } from "./ui/button";

const DownloadSummaryButton = ({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) => {
  const handleDownload = () => {
    const summaryContent = `#${title}
    Generated Summary

    Generated on :${new Date(createdAt).toLocaleDateString()}
    
    ${summaryText}
    
    Orignal File :${fileName}
    Generated by Sommaire`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  return <Button onClick={handleDownload}>Download ummary</Button>;
};

export default DownloadSummaryButton;
